// Generated by CIRCT firtool-1.147.0

// Include register initializers in init blocks unless synthesis is set	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:36:5
`ifndef RANDOMIZE	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:37:5
  `ifdef RANDOMIZE_REG_INIT	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:39:7
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:43:5
  `ifndef ENABLE_INITIAL_REG_	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:45:7
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS
	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:50:5
// Standard header to adapt well known macros for register randomization.	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:5:5

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:6:5
`ifndef RANDOM	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:7:5
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:11:5
`ifndef INIT_RANDOM	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:12:5
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:16:5
`ifndef RANDOMIZE_DELAY	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:17:5
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:21:5
`ifndef INIT_RANDOM_PROLOG_	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:22:5
  `ifdef RANDOMIZE	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:24:7
    `ifdef VERILATOR	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:25:9
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module xlnxstream_2018_3(	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:62:3
  input         M_AXIS_ACLK,	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:62:35
                M_AXIS_ARESETN,	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:62:57
  output        M_AXIS_TVALID,	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:62:83
  output [31:0] M_AXIS_TDATA,	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:62:107
  output [3:0]  M_AXIS_TSTRB,	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:62:131
  output        M_AXIS_TLAST,	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:62:154
  input         M_AXIS_TREADY	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:62:176
);

  wire        _GEN;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:139:11
  reg  [3:0]  read_pointer;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:136:21
  reg         axis_tvalid_delay;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:115:26
  reg  [4:0]  count;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:103:14
  reg  [1:0]  mst_exec_state;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:99:23
  wire        _GEN_0 = ~M_AXIS_ARESETN;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:79:10
  wire        _GEN_1 = mst_exec_state === 2'h0;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:69:14, :80:10, :100:11
  wire        _GEN_2 = mst_exec_state === 2'h1;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:67:14, :81:10, :100:11
  wire        _GEN_3 = ~_GEN_1 & M_AXIS_ARESETN;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:80:10, :83:10, :84:10
  wire        _GEN_4 = count != 5'h1F & _GEN_2 & _GEN_3;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:74:15, :81:10, :84:10, :89:11, :90:11, :104:11
  wire        _GEN_5 = ~_GEN_2 & _GEN_3 & mst_exec_state !== 2'h2;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:68:15, :81:10, :84:10, :94:11, :95:11, :96:11, :100:11
  wire [31:0] _GEN_6 = {28'h0, read_pointer};	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:76:15, :106:11, :137:11
  wire        _GEN_7 = _GEN_6 < 32'h8;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:77:15, :106:11, :107:11
  wire        _GEN_8 = mst_exec_state == 2'h2 & _GEN_7;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:68:15, :100:11, :105:11, :107:11, :108:11
  wire        _GEN_9 = ~axis_tvalid_delay | M_AXIS_TREADY;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:110:11, :111:11, :116:11
  reg         axis_tlast_delay;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:117:25
  wire        _GEN_10 = read_pointer == 4'h8;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:70:15, :119:11, :137:11
  wire        _GEN_11 = _GEN_7 & M_AXIS_ARESETN;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:107:11, :122:11
  wire        _GEN_12 = _GEN & _GEN_11;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:122:11, :123:11, :139:11
  wire        _GEN_13 = ~_GEN;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:128:11, :139:11
  wire        _GEN_14 = _GEN_11 & _GEN_13;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:122:11, :128:11, :129:11
  wire        _GEN_15 = ~_GEN_14;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:129:11, :130:11
  reg         tx_done;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:138:16
  assign _GEN = M_AXIS_TREADY & _GEN_8;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:108:11, :139:11
  reg  [31:0] stream_data_out;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:144:24
  always @(posedge M_AXIS_ACLK) begin	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:146:5
    if (_GEN_5) begin	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:96:11, :147:7
    end
    else	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:147:7
      mst_exec_state <=
        _GEN_4 ? 2'h1 : _GEN_0 ? 2'h0 : M_AXIS_ARESETN & _GEN_1 ? 2'h1 : 2'h2;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:67:14, :68:15, :69:14, :79:10, :80:10, :85:10, :86:10, :87:10, :90:11, :91:11, :149:9
    if (~(~_GEN_5 & (_GEN_4 | _GEN_0)) | _GEN_5) begin	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:79:10, :90:11, :93:11, :96:11, :97:11, :98:11, :101:11, :102:11, :151:7
    end
    else	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:151:7
      count <= _GEN_4 ? count + 5'h1 : _GEN_0 ? 5'h0 : count;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:64:14, :73:14, :79:10, :82:10, :88:10, :90:11, :92:11, :104:11, :153:9
    axis_tvalid_delay <= M_AXIS_ARESETN & _GEN_8;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:108:11, :112:11, :155:7
    if (_GEN_0 | _GEN_9)	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:79:10, :111:11, :114:11, :156:7
      axis_tlast_delay <= M_AXIS_ARESETN & _GEN_9 & read_pointer == 4'h7;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:72:14, :109:11, :111:11, :113:11, :137:11, :157:9
    if (~(_GEN_15 & (_GEN_12 | _GEN_0)) | _GEN_14) begin	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:79:10, :123:11, :125:11, :129:11, :130:11, :131:11, :134:11, :135:11, :159:7
    end
    else	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:159:7
      read_pointer <= _GEN_12 ? read_pointer + 4'h1 : _GEN_0 ? 4'h0 : read_pointer;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:63:14, :71:14, :79:10, :120:11, :121:11, :123:11, :124:11, :137:11, :161:9
    if (_GEN_15 & (_GEN_12 | _GEN_0 | _GEN_10))	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:79:10, :119:11, :123:11, :127:11, :130:11, :133:11, :163:7
      tx_done <= _GEN_15 & ~_GEN_12 & M_AXIS_ARESETN & _GEN_10;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:119:11, :123:11, :126:11, :130:11, :132:11, :164:9
    if (M_AXIS_ARESETN & _GEN_13) begin	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:128:11, :143:11, :166:7
    end
    else	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:166:7
      stream_data_out <= _GEN & M_AXIS_ARESETN ? _GEN_6 + 32'h1 : 32'h1;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:78:15, :106:11, :139:11, :140:11, :141:11, :142:11, :168:9
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:171:5
    `ifdef FIRRTL_BEFORE_INITIAL	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:173:9
      `FIRRTL_BEFORE_INITIAL	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:174:11
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:176:9
      automatic logic [31:0] _RANDOM[0:1];	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:181:24
      `ifdef INIT_RANDOM_PROLOG_	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:177:11
        `INIT_RANDOM_PROLOG_	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:178:13
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:180:11
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:183:25, :184:21, :185:21, :186:15
        end	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:67:14, :68:15, :69:14
        axis_tvalid_delay = _RANDOM[1'h0][0];	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:66:14, :188:19, :190:19, :191:19, :192:13
        axis_tlast_delay = _RANDOM[1'h0][1];	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:66:14, :188:19, :193:19, :194:19, :195:13
        tx_done = _RANDOM[1'h0][2];	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:66:14, :188:19, :196:19, :197:19, :198:13
        stream_data_out = {_RANDOM[1'h0][31:3], _RANDOM[1'h1][2:0]};	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:65:13, :66:14, :188:19, :189:19, :199:19, :200:19, :201:19, :202:19, :203:19, :204:13
      `endif // RANDOMIZE_REG_INIT
      mst_exec_state = 2'h0;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:69:14, :206:11
      count = 5'h0;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:64:14, :207:11
      read_pointer = 4'h0;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:63:14, :208:11
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:210:9
      `FIRRTL_AFTER_INITIAL	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:211:11
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign M_AXIS_TVALID = axis_tvalid_delay;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:116:11, :215:5
  assign M_AXIS_TDATA = stream_data_out;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:145:11, :215:5
  assign M_AXIS_TSTRB = 4'hF;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:75:15, :215:5
  assign M_AXIS_TLAST = axis_tlast_delay;	// /Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/initial-roundtrip/golden/design.sv.mlir:118:11, :215:5
endmodule

