#loc2 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":2:25)
#loc3 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":2:39)
#loc14 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":2:52)
"builtin.module"() ({
  "hw.module"() <{module_type = !hw.modty<input clk : i1, input d : i4, output q : i4>, parameters = [], result_locs = [#loc14], sym_name = "init_ff"}> ({
  ^bb0(%arg0: i1 loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":2:25), %arg1: i4 loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":2:39)):
    %0 = "hw.constant"() <{value = 5 : i4}> : () -> i4 loc(#loc4)
    %1 = "llhd.constant_time"() <{value = #llhd.time<0ns, 0d, 1e>}> : () -> !llhd.time loc(#loc5)
    %2 = "hw.constant"() <{value = 0 : i4}> : () -> i4 loc(#loc6)
    %3 = "llhd.sig"(%2) <{name = "q"}> : (i4) -> !llhd.ref<i4> loc(#loc7)
    "llhd.drv"(%3, %0, %1) : (!llhd.ref<i4>, i4, !llhd.time) -> () loc(#loc8)
    %4 = "seq.to_clock"(%arg0) : (i1) -> !seq.clock loc(#loc9)
    %5 = "seq.firreg"(%arg1, %4) <{name = "q"}> : (i4, !seq.clock) -> i4 loc(#loc10)
    "llhd.drv"(%3, %5, %1) : (!llhd.ref<i4>, i4, !llhd.time) -> () loc(#loc11)
    %6 = "llhd.prb"(%3) : (!llhd.ref<i4>) -> i4 loc(#loc12)
    "hw.output"(%6) : (i4) -> () loc(#loc13)
  }) : () -> () loc(#loc1)
}) : () -> () loc(#loc)
#loc = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":1:1)
#loc1 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":2:3)
#loc4 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":3:14)
#loc5 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":4:10)
#loc6 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":5:14)
#loc7 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":6:10)
#loc8 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":7:5)
#loc9 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":8:10)
#loc10 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":9:12)
#loc11 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":10:5)
#loc12 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":11:10)
#loc13 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-hw/design.mlir":12:5)

