#loc2 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":2:25)
#loc3 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":2:39)
#loc32 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":2:52)
"builtin.module"() ({
  "hw.module"() <{module_type = !hw.modty<input clk : i1, input d : i4, output q : i4>, parameters = [], result_locs = [#loc32], sym_name = "init_ff"}> ({
  ^bb0(%arg0: i1 loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":2:25), %arg1: i4 loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":2:39)):
    %0 = "llhd.constant_time"() <{value = #llhd.time<0ns, 1d, 0e>}> : () -> !llhd.time loc(#loc4)
    %1 = "hw.constant"() <{value = true}> : () -> i1 loc(#loc5)
    %2 = "llhd.constant_time"() <{value = #llhd.time<0ns, 0d, 1e>}> : () -> !llhd.time loc(#loc6)
    %3 = "hw.constant"() <{value = 0 : i4}> : () -> i4 loc(#loc7)
    %4 = "hw.constant"() <{value = 5 : i4}> : () -> i4 loc(#loc8)
    %5 = "hw.constant"() <{value = false}> : () -> i1 loc(#loc9)
    %6 = "llhd.sig"(%5) <{name = "clk"}> : (i1) -> !llhd.ref<i1> loc(#loc10)
    %7 = "llhd.prb"(%6) : (!llhd.ref<i1>) -> i1 loc(#loc11)
    %8 = "llhd.sig"(%3) <{name = "d"}> : (i4) -> !llhd.ref<i4> loc(#loc12)
    %9 = "llhd.sig"(%3) <{name = "q"}> : (i4) -> !llhd.ref<i4> loc(#loc13)
    "llhd.process"() ({
      "llhd.drv"(%9, %4, %2) : (!llhd.ref<i4>, i4, !llhd.time) -> () loc(#loc15)
      "llhd.halt"() : () -> () loc(#loc16)
    }) : () -> () loc(#loc14)
    "llhd.process"() ({
      "cf.br"()[^bb1] : () -> () loc(#loc18)
    ^bb1:  // 3 preds: ^bb0, ^bb2, ^bb3
      %11 = "llhd.prb"(%6) : (!llhd.ref<i1>) -> i1 loc(#loc19)
      "llhd.wait"(%7)[^bb2] <{operandSegmentSizes = array<i32: 0, 0, 1, 0>}> : (i1) -> () loc(#loc20)
    ^bb2:  // pred: ^bb1
      %12 = "llhd.prb"(%6) : (!llhd.ref<i1>) -> i1 loc(#loc21)
      %13 = "comb.xor"(%11, %1) <{twoState}> : (i1, i1) -> i1 loc(#loc22)
      %14 = "comb.and"(%13, %12) <{twoState}> : (i1, i1) -> i1 loc(#loc23)
      "cf.cond_br"(%14)[^bb3, ^bb1] <{operandSegmentSizes = array<i32: 1, 0, 0>}> : (i1) -> () loc(#loc24)
    ^bb3:  // pred: ^bb2
      %15 = "llhd.prb"(%8) : (!llhd.ref<i4>) -> i4 loc(#loc25)
      "llhd.drv"(%9, %15, %0) : (!llhd.ref<i4>, i4, !llhd.time) -> () loc(#loc26)
      "cf.br"()[^bb1] : () -> () loc(#loc27)
    }) : () -> () loc(#loc17)
    "llhd.drv"(%6, %arg0, %2) : (!llhd.ref<i1>, i1, !llhd.time) -> () loc(#loc28)
    "llhd.drv"(%8, %arg1, %2) : (!llhd.ref<i4>, i4, !llhd.time) -> () loc(#loc29)
    %10 = "llhd.prb"(%9) : (!llhd.ref<i4>) -> i4 loc(#loc30)
    "hw.output"(%10) : (i4) -> () loc(#loc31)
  }) : () -> () loc(#loc1)
}) : () -> () loc(#loc)
#loc = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":1:1)
#loc1 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":2:3)
#loc4 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":3:10)
#loc5 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":4:13)
#loc6 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":5:10)
#loc7 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":6:14)
#loc8 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":7:14)
#loc9 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":8:14)
#loc10 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":9:14)
#loc11 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":10:10)
#loc12 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":11:12)
#loc13 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":12:10)
#loc14 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":13:5)
#loc15 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":14:7)
#loc16 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":15:7)
#loc17 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":17:5)
#loc18 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":18:7)
#loc19 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":20:12)
#loc20 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":21:7)
#loc21 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":23:12)
#loc22 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":24:12)
#loc23 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":25:12)
#loc24 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":26:7)
#loc25 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":28:12)
#loc26 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":29:7)
#loc27 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":30:7)
#loc28 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":32:5)
#loc29 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":33:5)
#loc30 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":34:10)
#loc31 = loc("/Users/bytedance/cym/cymProject/k-circt-top-repo/services/kcirct-exp/external-defects/.work/complete-exp/alt-frontend/initial-block-llhd/design.mlir":35:5)

